<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="USBLRCKUMARSIN6" ignored="0" name="Default test" tests="10" failures="1" timestamp="22 Aug 2018 10:52:49 GMT" time="231.395" errors="0">
  <testcase name="TC01AllBtnsDsplyd_Test" time="0.058" classname="com.hpi.test.SanitySuiteExecution.ContactSupport_SanityExecution"/>
  <testcase name="TC_ClickFndOutMoreLink_Test" time="0.155" classname="com.hpi.test.SanitySuiteExecution.ContactSupport_SanityExecution">
    <failure type="java.lang.AssertionError" message="expected [https://uat.support.hp.com/us-en/document/c05061199] but found [https://support.hp.com/us-en/document/c05061199]">
      <![CDATA[java.lang.AssertionError: expected [https://uat.support.hp.com/us-en/document/c05061199] but found [https://support.hp.com/us-en/document/c05061199]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.hpi.test.SanitySuiteExecution.ContactSupport_SanityExecution.TC_ClickFndOutMoreLink_Test(ContactSupport_SanityExecution.java:87)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_ClickFndOutMoreLink_Test -->
  <testcase name="TC_DesktopLanding_Test" time="0.282" classname="com.hpi.test.SanitySuiteExecution.ContactSupport_SanityExecution"/>
  <testcase name="TC_LaptopLanding_Test" time="0.323" classname="com.hpi.test.SanitySuiteExecution.ContactSupport_SanityExecution"/>
  <testcase name="TC_PrinterLanding_Test" time="0.293" classname="com.hpi.test.SanitySuiteExecution.ContactSupport_SanityExecution"/>
  <testcase name="TC_VerifyDesktopSubmitBtn_Test" time="0.392" classname="com.hpi.test.SanitySuiteExecution.ContactSupport_SanityExecution"/>
  <testcase name="TC_VerifyLaptopSubmitBtn_Test" time="0.427" classname="com.hpi.test.SanitySuiteExecution.ContactSupport_SanityExecution"/>
  <testcase name="TC_VerifyPrinterProductLabel_Test" time="2.408" classname="com.hpi.test.SanitySuiteExecution.ContactSupport_SanityExecution"/>
  <testcase name="TC_VerifyPrinterSubmitBtn_Test" time="0.371" classname="com.hpi.test.SanitySuiteExecution.ContactSupport_SanityExecution"/>
  <testcase name="TC_PrinterSNTest" time="6.823" classname="com.hpi.test.SanitySuiteExecution.ContactSupport_SanityExecution"/>
</testsuite> <!-- Default test -->
