<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="18" total="19" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="56966" started-at="2018-06-18T17:24:03Z" finished-at="2018-06-18T17:25:00Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="56966" started-at="2018-06-18T17:24:03Z" finished-at="2018-06-18T17:25:00Z">
      <class name="com.hpi.test.SanitySuiteExecution.ContactSupport_SanityExecution">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.hpi.test.SanitySuiteExecution.ContactSupport_SanityExecution@4b553d26]" name="setup" is-config="true" duration-ms="17981" started-at="2018-06-18T17:24:03Z" finished-at="2018-06-18T17:24:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="TC09_EP_PNameTest()[pri:8, instance:com.hpi.test.SanitySuiteExecution.ContactSupport_SanityExecution@4b553d26]" name="TC09_EP_PNameTest" duration-ms="37420" started-at="2018-06-18T17:24:21Z" finished-at="2018-06-18T17:24:58Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [HP Customer Support - Verify entitlement] but found [Welcome to HP Customer Support]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [HP Customer Support - Verify entitlement] but found [Welcome to HP Customer Support]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.hpi.test.SanitySuiteExecution.ContactSupport_SanityExecution.TC09_EP_PNameTest(ContactSupport_SanityExecution.java:136)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC09_EP_PNameTest -->
        <test-method status="PASS" signature="screenshot(org.testng.ITestResult)[pri:0, instance:com.hpi.test.SanitySuiteExecution.ContactSupport_SanityExecution@4b553d26]" name="screenshot" is-config="true" duration-ms="1537" started-at="2018-06-18T17:24:58Z" finished-at="2018-06-18T17:25:00Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=TC09_EP_PNameTest status=FAILURE method=ContactSupport_SanityExecution.TC09_EP_PNameTest()[pri:8, instance:com.hpi.test.SanitySuiteExecution.ContactSupport_SanityExecution@4b553d26] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- screenshot -->
      </class> <!-- com.hpi.test.SanitySuiteExecution.ContactSupport_SanityExecution -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
